# Generated by Django 3.2.6 on 2022-08-26 10:46

import blockchain.validators
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('listIndexBlockRecieved', models.TextField(null=True)),
                ('listIndexBlockSent', models.TextField(null=True)),
                ('privateKey', models.CharField(max_length=128, null=True)),
                ('publicKey', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousHash', models.CharField(max_length=128, null=True)),
                ('index', models.IntegerField(default=0, null=True)),
                ('validation', models.BooleanField(default=False)),
                ('text', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('score', models.IntegerField(default=0, validators=[blockchain.validators.validar_gt_0, blockchain.validators.validar_lt_10])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=128, null=True)),
                ('emiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emiters', to='blockchain.member')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='blockchain.member')),
            ],
        ),
    ]
