# Generated by Django 3.2.6 on 2022-08-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='listIndexBlockRecieved',
        ),
        migrations.RemoveField(
            model_name='member',
            name='listIndexBlockSent',
        ),
        migrations.AlterField(
            model_name='block',
            name='emiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emited', to='blockchain.member'),
        ),
        migrations.AlterField(
            model_name='block',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received', to='blockchain.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='privateKey',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='publicKey',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
