# Generated by Django 3.2.6 on 2022-08-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20220828_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='previousHash',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
