# Generated by Django 3.2.6 on 2022-08-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20220828_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
